### PR TITLE
update jwt packages

### PR DESCRIPTION
**Pull request by Awk34**
jwt packages have been updated due to security vulnerabilities

### CODE REVIEW

**Comment by andrewstuart** [comment]
Awesome, thanks!

I had no idea the versions had jumped so far, either.

**Comment by Awk34** [comment]
Yeah, surprisingly nothing breaks in the project when updating.

On a side note, I see that @DaftMonk also joined the organization that I made. Hopefully he'll transfer the ownership of the original repo to the organization so I can merge PRs :/

**Comment by andrewstuart** [comment]
Nice, although there's still going to be difficulty as far as I know getting the changes pushed to NPM. One of the things I'd really like to do is to set up Travis or some build server to push to NPM. That way, the project can move forward independent of the ebb and flow of peoples' time. At least, as long as some contributors are still active.

**Comment by Awk34** [comment]
Yeah I would love to get that set up. We use Jenkins at work, but I've been wanting to learn more about Travis.

**Pull request merged**
